import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'gateway-client';
}
// main.ts or app.component.ts
const tokenKey = 'access_token';
if (!localStorage.getItem(tokenKey)) {
  localStorage.setItem(tokenKey, 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIwR0xUX3YyUTU3QW5uNHpJaWt1UWZCb3FSTkItVXI1SUE3cFpNTDVOVWVrIn0.eyJleHAiOjE3NDQwMTI1MzAsImlhdCI6MTc0NDAxMjIzMCwianRpIjoiNzM0YWIyM2EtNWE2Yi00ZmEzLThiNjMtMTc5ODBjZjQxMmMyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9yZWZ1bmQtcmVhbG0iLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMDM1NmIyYmQtNGU2Zi00MjY0LWE5ZGYtZWU1MTI1OWZjNTcyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiQXBpZ2F0d2F5NHNhZTEwIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXJlZnVuZC1yZWFsbSJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIHByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImNsaWVudEhvc3QiOiIxNzIuMTguMC4xIiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LWFwaWdhdHdheTRzYWUxMCIsImNsaWVudEFkZHJlc3MiOiIxNzIuMTguMC4xIiwiY2xpZW50X2lkIjoiQXBpZ2F0d2F5NHNhZTEwIn0.h5PNA_L0WXNkoOAc8LCaMoI56TREBqJKyNWgrsMp-TMKGsFxVkRodaFy1-q2WxZF5QDtw134XrmNMaQDPsocYuD7wnp-mQWgQqtYO3_9lalyzzCrBnCfbWINon7r00m7LQbsfNYt8BMpz9IydXoD8kb7oKhe3yPOZ0k2LQqry3em8RdqHiGpiSpmjJ0Bo3vR_HB-RJVGo92jk2fLUf2lAEZ4Nw6uLIHj-ShUndroG4G5tB2It9zUneTOiRSWLZqKf-8bVOD5nhGAgOANtEr4F4LnVx0eCwYzUcdMkGr9bwKv9iE_G5wuKGwB6_hU9N54rJzPYecURvVeIxrr8A4pcQ'); // your token
}
